spring.application.name=yadot-api

# ==========================================
# 1. CONEXÃO COM O BANCO
# ARMA SECRETA 1: Adicionamos "?sslmode=require" no final da URL.
# Bancos em nuvem rejeitam conexões que não são seguras!
# ==========================================
spring.datasource.url=jdbc:postgresql://db.orhlbsbhoniqhsdshqsg.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=yadot@dbaacess
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 2. CONFIGURAÇÃO DO JPA / HIBERNATE
# ARMA SECRETA 2: Mandar o Hibernate calar a boca e aceitar que é PostgreSQL,
# sem precisar bater no banco antes pra perguntar.
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop